export const OBJECT_STORAGE_SERVICE = Symbol('OBJECT_STORAGE_SERVICE');
export const IMAGE_PROCESSOR_SERVICE = Symbol('IMAGE_PROCESSOR_SERVICE');
export const MEDIA_URL_BUILDER = Symbol('MEDIA_URL_BUILDER');
