export const ERROR_CODES = {
  CONTACT_DEFAULT_DELETE_FORBIDDEN: 'CONTACT_DEFAULT_DELETE_FORBIDDEN',
  INVALID_AVAILABILITY_RANGE: 'INVALID_AVAILABILITY_RANGE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
