export const ERROR_CODES = {
  CONTACT_DEFAULT_DELETE_FORBIDDEN: 'CONTACT_DEFAULT_DELETE_FORBIDDEN',
  INVALID_AVAILABILITY_RANGE: 'INVALID_AVAILABILITY_RANGE',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',
  USER_DISABLED: 'USER_DISABLED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} satisfies Record<string, string>;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
