export const ERROR_CODES = {
  CONTACT_DEFAULT_DELETE_FORBIDDEN: 'CONTACT_DEFAULT_DELETE_FORBIDDEN',
  INVALID_AVAILABILITY_RANGE: 'INVALID_AVAILABILITY_RANGE',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
} satisfies Record<string, string>;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
